name: CI

on:
  push:
    branches:
      - master

jobs:

  win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - run: yarn install
      - run: yarn pack
        env:
          NODE_ENV: production

  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - run: yarn install
      - run: yarn pack
        env:
          NODE_ENV: production

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - run: yarn install
      - run: yarn pack
        env:
          NODE_ENV: production